project_name: logschema

builds:
  - id: cli
    binary: logschema
    main: cmd/logschema/main.go
    goos:
      - windows
      - darwin
      - linux
archives:
  - id: cli
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
